# Generated by Django 2.2.1 on 2020-07-24 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(max_length=200)),
                ('domain_description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='DomainTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_id', models.IntegerField()),
                ('domain_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gyaan.Domain')),
            ],
        ),
        migrations.CreateModel(
            name='DomainRequests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_by', models.IntegerField()),
                ('is_approved', models.BooleanField(default=False)),
                ('domain_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gyaan.Domain')),
            ],
        ),
        migrations.CreateModel(
            name='DomainPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('post_id', models.IntegerField()),
                ('is_approved', models.BooleanField(default=False)),
                ('domain_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gyaan.Domain')),
            ],
        ),
        migrations.CreateModel(
            name='DomainExperts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_expert_id', models.IntegerField()),
                ('domain_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gyaan.Domain')),
            ],
        ),
    ]
