# Generated by Django 2.2.1 on 2020-07-24 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gyaan', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='domainexperts',
            old_name='domain_id',
            new_name='domain',
        ),
        migrations.RenameField(
            model_name='domainpost',
            old_name='domain_id',
            new_name='domain',
        ),
        migrations.RenameField(
            model_name='domainrequests',
            old_name='domain_id',
            new_name='domain',
        ),
        migrations.RenameField(
            model_name='domaintag',
            old_name='domain_id',
            new_name='domain',
        ),
    ]
